// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9aHT3pdY57qy1ft3-aPDhwPMDy9coIq4',
    appId: '1:354544368265:android:f52bfffc4a36ba75d16458',
    messagingSenderId: '354544368265',
    projectId: 'newmedkenes',
    storageBucket: 'newmedkenes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXptAKEQbDJbGDsszUtvr6T1WeFbc49Ww',
    appId: '1:354544368265:ios:2904e947687333c5d16458',
    messagingSenderId: '354544368265',
    projectId: 'newmedkenes',
    storageBucket: 'newmedkenes.firebasestorage.app',
    iosBundleId: 'com.example.medkenes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXptAKEQbDJbGDsszUtvr6T1WeFbc49Ww',
    appId: '1:354544368265:ios:2904e947687333c5d16458',
    messagingSenderId: '354544368265',
    projectId: 'newmedkenes',
    storageBucket: 'newmedkenes.firebasestorage.app',
    iosBundleId: 'com.example.medkenes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcIWml5hQa8dOTWA_Ugq9WV_ZzVs19BFo',
    appId: '1:354544368265:web:f143c2a795ee9158d16458',
    messagingSenderId: '354544368265',
    projectId: 'newmedkenes',
    authDomain: 'newmedkenes.firebaseapp.com',
    storageBucket: 'newmedkenes.firebasestorage.app',
    measurementId: 'G-5QECZ5G8C3',
  );
}
